version: '3.9'

services:
  lab-implantacion-db:
    image: postgres:14
    container_name: lab-implantacion-postgres
    restart: unless-stopped
    env_file: .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - lab_implantacion_postgres_data:/var/lib/postgresql/data
    networks:
      - implantacion-net

  lab-implantacion-api:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    container_name: lab-implantacion-api
    depends_on:
      - lab-implantacion-db
    environment:
      DB_HOST: lab-implantacion-db
      DB_PORT: 5432
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8090:8090"
    networks:
      - implantacion-net

volumes:
  lab_implantacion_postgres_data:

networks:
  implantacion-net:
    driver: bridge
